[package]
name = "vigil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
opencv = "0.84.2"
tch = "0.13.0"
torch-sys = "0.13.0"
ndarray = "0.15.0"